### ISSUE TITLE
dbg function in awesome 3.5

### ISSUE THREAD

**Issue by quizzmaster** [vincentbernat/awesome-configuration#3]
The dbg function in debug.lua does not work with awesome 3.5/Lua 5.2. May you have an idea for me to fix this problem, cause the function ist really nice

**Comment by P-EB** [comment]
@vincentbernat maybe you should close this issue?

**Comment by vincentbernat** [comment]
Is Mod-i working on your branch?

**Comment by P-EB** [comment]
Yes. Even though it's not funny as I don't know how to close these naughty.notify. :P

**Comment by vincentbernat** [comment]
❦  6 janvier 2016 07:02 -0800, Pierre-Elliott Bécue <notifications@github.com> :

> Yes. Even though it's not funny as I don't know how to close these
> naughty.notify. :P

They should close when clicking on them. But I suppose you already
tried. :)
-- 
Use the fundamental control flow constructs.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by P-EB** [comment]
Guess what, it was my gnome wrapper. Solved the issue by restarting the whole in a clean awesome session without gnome sugar.

Sry for noise.
